### ISSUE TITLE
Is there any plan to share paper or tutorial ?

### ISSUE THREAD

**Issue by Tarpelite** [NLPInBLCU/BiaffineDependencyParsing#7]
Hi,
I'm really interested in your work and I have recently worked at using BERT to do parsing,
But I am a little fresh about how to deal with the tokenizing and the decoding, 

So do you have any plan to release a paper or do any tutorial?

**Comment by LiangsLi** [comment]
Hi， @Tarpelite 
I am very honored to know that you are interested in this project. Since this project has a lot of follow-up work to do, and I have other work in progress, we have no plans to write a tutorial in the near future. 
Although we haven't published a paper yet, there is a lot of similar work at EMNLP 2019 and other conferences. You can refer to the following papers:

- Beto, Bentz, Becas: The Surprising Cross-Lingual Effectiveness of BERT
- Multilingual Constituency Parsing with Self-Attention and Pre-Training
- 75 Languages, 1 Model: Parsing Universal Dependencies Universally
- Cross-Lingual BERT Transformation for Zero-Shot Dependency Parsing

In addition, Stanford has released a great dependency parser, and our decoder also refers to their implementation, you can refer to [stanfordnlp](https://github.com/stanfordnlp/stanfordnlp).

hope this helps~

**Comment by Tarpelite** [comment]
Thanks for your very detailed helpful suggestions. 😃
